In [43]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

plt.rcParams['font.family'] = 'Malgun Gothic'

df = pd.read_csv('./train.csv')
df

회계년도  거래소코드    PBR      PER  기업규모코드          매출액  매출액순이익률  매출액증가율  \
0     2011  58820  2.210    0.000    20.0   17751704.0    -8.50   56.40   
1     2012  58820  2.555    0.000    20.0   16255389.0   -40.97   -8.43   
2     2013  58820  2.945  375.055    20.0   20402140.0     1.45   25.51   
3     2014  58820  2.855  435.355    20.0   22752584.0     0.69   11.52   
4     2015  58820  5.915    0.000    20.0   27041894.0   -13.50   18.85   
...    ...    ...    ...      ...     ...          ...      ...     ...   
7548  2013  25530  0.735  435.355    30.0  186255266.0     8.90   -1.97   
7549  2014  25530  0.635    9.805    30.0  161934964.0    10.45  -13.06   
7550  2015  25530  0.630    7.085    30.0  185141914.0    13.39   14.33   
7551  2016  25530  0.630   14.515    30.0  181367297.0     8.36   -2.04   
7552  2017  25530  0.550    5.130    30.0  169845355.0    11.37   -6.35   

           성장비용        영업손익  자기자본회전률      종가  주당순손익  총자본회전률          회사명  \
0      376118.0    640283.0     0.97   785.0  -35.0    0.66     (주)CMG제약   
1      401085.0  -4205503.0     0.66  1330.0 -138.0    0.39     (주)CMG제약   
2      243898.0    791250.0     0.51   932.0    0.0    0.36     (주)CMG제약   
3      215128.0    442322.0     0.46   912.0    2.0    0.40     (주)CMG제약   
4      195671.0  -2572168.0     0.56  2110.0  -42.0    0.47     (주)CMG제약   
...         ...         ...      ...     ...    ...     ...          ...   
7548  3573572.0  20107873.0     0.96  4950.0    0.0    0.81  (주)에스제이엠홀딩스   
7549  5748432.0  20730328.0     0.81  4660.0    0.0    0.69  (주)에스제이엠홀딩스   
7550        0.0  23545362.0     0.88  5810.0    0.0    0.74  (주)에스제이엠홀딩스   
7551        0.0  13611422.0     0.81  5220.0    0.0    0.67  (주)에스제이엠홀딩스   
7552        0.0  10445486.0     0.72  4800.0    0.0    0.60  (주)에스제이엠홀딩스   

        부채자본비율  현금흐름스코어         수익률  투자신호        PEG  
0     0.506132        1   69.426752     1   0.000000  
1     0.803292        1  -29.924812     0   0.000000  
2     0.140951        0   -2.145923     0  14.256033  
3     0.184647        2  131.359649     1  23.557141  
4     0.207355        2   50.710900     1   0.000000  
...        ...      ...         ...   ...        ...  
7548  0.018116        2   -5.858586     0  -5.993485  
7549  0.018116        2   24.678112     1  -2.618242  
7550  0.098414        2  -10.154905     0   0.101062  
7551  0.104776        2   -8.045977     0   0.066509  
7552  0.101177        1  -28.645833     0   0.203981  

[7553 rows x 20 columns]

In [45]:
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split,RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, precision_score, recall_score,roc_auc_score, mean_squared_error

from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_score

import warnings 
warnings.filterwarnings("ignore")

In [46]:
df = pd.get_dummies(df, columns=['기업규모코드'])

In [47]:
# 피쳐와 타겟 설정

X = df.drop(['투자신호', '회사명', '종가', '회계년도', '거래소코드', '수익률'], axis=1)
y = df["투자신호"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=22,stratify=y)

In [50]:
from sklearn.preprocessing import RobustScaler, MinMaxScaler, StandardScaler


scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_val = scalar.fit_transform(X_val)

In [51]:
from sklearn import metrics

def modeling(model, X_train, X_val, y_train, y_val):
    model.fit(X_train,y_train)
    pred = model.predict(X_val)
    print(classification_report(y_val, pred))
    print(confusion_matrix(y_val, pred))
    

de_clf = DecisionTreeClassifier(random_state=200)
ra_clf =RandomForestClassifier(random_state=200)
xgb = XGBClassifier()
log = LogisticRegression(random_state=200)

In [52]:
modeling(de_clf, X_train, X_val, y_train, y_val)

              precision    recall  f1-score   support

           0       0.58      0.59      0.59       876
           1       0.42      0.42      0.42       635

    accuracy                           0.52      1511
   macro avg       0.50      0.50      0.50      1511
weighted avg       0.52      0.52      0.52      1511

[[516 360]
 [370 265]]


In [53]:
modeling(log, X_train, X_val, y_train, y_val)

              precision    recall  f1-score   support

           0       0.58      0.98      0.73       876
           1       0.58      0.03      0.07       635

    accuracy                           0.58      1511
   macro avg       0.58      0.51      0.40      1511
weighted avg       0.58      0.58      0.45      1511

[[860  16]
 [613  22]]


In [54]:
modeling(ra_clf, X_train, X_val, y_train, y_val)

              precision    recall  f1-score   support

           0       0.61      0.86      0.71       876
           1       0.55      0.24      0.34       635

    accuracy                           0.60      1511
   macro avg       0.58      0.55      0.52      1511
weighted avg       0.59      0.60      0.55      1511

[[753 123]
 [482 153]]


In [55]:
modeling(xgb, X_train, X_val, y_train, y_val)

              precision    recall  f1-score   support

           0       0.60      0.71      0.65       876
           1       0.46      0.34      0.39       635

    accuracy                           0.56      1511
   macro avg       0.53      0.53      0.52      1511
weighted avg       0.54      0.56      0.54      1511

[[626 250]
 [420 215]]


In [57]:
df_t = pd.read_csv('./test.csv')
df_t

회계년도   거래소코드    PBR      PER  기업규모코드           매출액  매출액순이익률  매출액증가율  \
0     2018   58820  7.185  113.690    30.0  4.986478e+07    12.16   20.05   
1     2018     590  0.585   56.590    30.0  1.225509e+08    10.32    1.32   
2     2018   10120  1.780   16.090    10.0  2.484978e+09     5.32    6.03   
3     2018   11070  1.865   23.410    10.0  7.982104e+09     2.04    4.46   
4     2018    1940  0.290   13.505    30.0  1.314755e+09     2.76    7.66   
...    ...     ...    ...      ...     ...           ...      ...     ...   
1074  2018   10580  1.705   15.820    20.0  7.399840e+07    -1.81  -58.01   
1075  2018   41510  2.685   81.095    30.0  6.122275e+08     3.83   67.56   
1076  2018    4060  0.820   27.880    30.0  3.202022e+08     2.09   12.18   
1077  2018  123700  0.465   25.870    20.0  1.552595e+08     2.40   -4.81   
1078  2018   25530  0.400   16.740    20.0  1.607407e+08     3.83   -5.36   

            성장비용         영업손익  자기자본회전률       종가  주당순손익  총자본회전률           회사명  \
0       505130.0    2567820.0     0.49   4235.0    0.0    0.45      (주)CMG제약   
1            0.0   13319440.0     0.45  63900.0    0.0    0.40      CS홀딩스(주)   
2     16628000.0  205047548.0     2.03  49000.0    0.0    1.07     LS일렉트릭(주)   
3            0.0  263517410.0     3.92  86400.0    0.0    1.37      LG이노텍(주)   
4            0.0   62375860.0     1.04  13750.0    0.0    0.87   KISCO홀딩스(주)   
...          ...          ...      ...      ...    ...     ...           ...   
1074    762348.0   -1016490.0     1.12    680.0  -89.0    0.82      (주)에스엠벡셀   
1075  23694980.0   47746037.0     1.21  52300.0    0.0    0.68  (주)에스엠엔터테인먼트   
1076   1226233.0    3937720.0     1.64    736.0   33.0    0.97    (주)에스지세계물산   
1077         0.0     742003.0     0.92   3020.0    0.0    0.77      (주)에스제이엠   
1078         0.0    1780439.0     0.66   3425.0    0.0    0.55   (주)에스제이엠홀딩스   

        부채자본비율  현금흐름스코어        수익률  투자신호       PEG  
0     0.099999        1   0.354191     0  2.302342  
1     0.046186        2  -8.450704     0 -1.239002  
2     0.814721        1  11.428571     1  0.812819  
3     1.633317        2  62.037037     1  0.541023  
4     0.018116        2  -6.909091     0 -0.266356  
...        ...      ...        ...   ...       ...  
1074  1.375648        1  23.382353     1  0.441852  
1075  0.385989        2 -26.481836     0  2.246915  
1076  0.685426        0  22.826087     1  0.956655  
1077  0.148879        2  27.152318     1 -0.845054  
1078  0.099447        2  -5.547445     0 -0.519606  

[1079 rows x 20 columns]

In [58]:
df_tt = df_t.drop('투자신호', axis=1)

In [59]:
df_tt

회계년도   거래소코드    PBR      PER  기업규모코드           매출액  매출액순이익률  매출액증가율  \
0     2018   58820  7.185  113.690    30.0  4.986478e+07    12.16   20.05   
1     2018     590  0.585   56.590    30.0  1.225509e+08    10.32    1.32   
2     2018   10120  1.780   16.090    10.0  2.484978e+09     5.32    6.03   
3     2018   11070  1.865   23.410    10.0  7.982104e+09     2.04    4.46   
4     2018    1940  0.290   13.505    30.0  1.314755e+09     2.76    7.66   
...    ...     ...    ...      ...     ...           ...      ...     ...   
1074  2018   10580  1.705   15.820    20.0  7.399840e+07    -1.81  -58.01   
1075  2018   41510  2.685   81.095    30.0  6.122275e+08     3.83   67.56   
1076  2018    4060  0.820   27.880    30.0  3.202022e+08     2.09   12.18   
1077  2018  123700  0.465   25.870    20.0  1.552595e+08     2.40   -4.81   
1078  2018   25530  0.400   16.740    20.0  1.607407e+08     3.83   -5.36   

            성장비용         영업손익  자기자본회전률       종가  주당순손익  총자본회전률           회사명  \
0       505130.0    2567820.0     0.49   4235.0    0.0    0.45      (주)CMG제약   
1            0.0   13319440.0     0.45  63900.0    0.0    0.40      CS홀딩스(주)   
2     16628000.0  205047548.0     2.03  49000.0    0.0    1.07     LS일렉트릭(주)   
3            0.0  263517410.0     3.92  86400.0    0.0    1.37      LG이노텍(주)   
4            0.0   62375860.0     1.04  13750.0    0.0    0.87   KISCO홀딩스(주)   
...          ...          ...      ...      ...    ...     ...           ...   
1074    762348.0   -1016490.0     1.12    680.0  -89.0    0.82      (주)에스엠벡셀   
1075  23694980.0   47746037.0     1.21  52300.0    0.0    0.68  (주)에스엠엔터테인먼트   
1076   1226233.0    3937720.0     1.64    736.0   33.0    0.97    (주)에스지세계물산   
1077         0.0     742003.0     0.92   3020.0    0.0    0.77      (주)에스제이엠   
1078         0.0    1780439.0     0.66   3425.0    0.0    0.55   (주)에스제이엠홀딩스   

        부채자본비율  현금흐름스코어        수익률       PEG  
0     0.099999        1   0.354191  2.302342  
1     0.046186        2  -8.450704 -1.239002  
2     0.814721        1  11.428571  0.812819  
3     1.633317        2  62.037037  0.541023  
4     0.018116        2  -6.909091 -0.266356  
...        ...      ...        ...       ...  
1074  1.375648        1  23.382353  0.441852  
1075  0.385989        2 -26.481836  2.246915  
1076  0.685426        0  22.826087  0.956655  
1077  0.148879        2  27.152318 -0.845054  
1078  0.099447        2  -5.547445 -0.519606  

[1079 rows x 19 columns]

In [63]:
df_tt = pd.get_dummies(df_tt, columns=['기업규모코드']) 

In [66]:
df_tt.drop(['회사명', '종가', '회계년도', '거래소코드', '수익률'], axis=1, inplace=True)

In [67]:
m = model.predict(df_tt)
m

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [73]:
pred = pd.DataFrame(m)

In [74]:
pred

0
0     0
1     0
2     0
3     0
4     1
...  ..
1074  0
1075  0
1076  0
1077  0
1078  1

[1079 rows x 1 columns]

In [75]:
pred.value_counts()

0    887
1    192
dtype: int64

In [76]:
df_t['투자신호'].value_counts()

0    664
1    415
Name: 투자신호, dtype: int64